# =============================
# OpenDuck Server Configuration
# =============================


# Server network settings
openduck.host=0.0.0.0
openduck.port=8815

openduck.db=.\\data\\openduck.duckdb
metadatadb.db=.\\metadata\\metadata.duckdb

# Max memory for Arrow buffers in MB
arrow.memory.mb=512


# TLS / SSL settings
tls.enabled=true
tls.certFile=certs/server-cert.pem
tls.keyFile=certs/server-key.pem

# Arrow Flight memory allocator (in MB)
arrow.memory.mb=512

# Logging (optional)
log.level=INFO
log.file=logs/openduck.log

# REST API
openduck.rest.port=8084
